### ISSUE TITLE
Question sur les Défis Hilo

### ISSUE THREAD

**Issue by hugovanier** [SanterreJo/homebridge-hilo#11]
Salut Jonathan.
Premièrement, merci beaucoup pour ton plug-in.
Il fonctionne parfaitement et ça me sera bien utile cette hiver.
Mon HomeKit se déconnecte souvent de Homebridge, mais c’est clairement pas ton plug-in le problème. Enfin bref.

L’hiver approche et je commence à me demander comment je vais jongler entre mes automatisations HomeKit et les défis Hilo…faire en sorte de ne pas by-passer les réglages de température établie par un defi.

Donc avant de me lancer dans cette analyse, je me demandais si tu y avais déjà pensé.

**Comment by SanterreJo** [comment]
@hugovanier Je suis un nouvel utilisateur d'Hilo depuis cet été, donc je n'ai pas d'expérience avec les défis encore. Mon hypothèse est qu'étant donné que le plugin n'a pas connaissance des défis Hilo, si tu as des automatisations homekit, elles vont prendre le dessus sur les défis.

Je laisse cette issue ouverte jusqu'à qu'on puisse documenter le comportement.

**Comment by jfmeuniercow** [comment]
Bonjour Jo,

En fait, il faudrait avoir un capteur pour nous dire l'état du défi. Si le défi est ouvert, nous pourrions faire une automatisation. Il y avait cela sur le plugin sur Home assistant. Malheureusement, qui ne marche pas pour moi. TU peux voir sur https://github.com/dvd-dev/hilo/

Features

Support for switches and dimmers as light devices
Get current and set target temperature of thermostat
Get energy usage of pretty much each devices
Generates energy meters and sensors
Sensor for Hilo Events (challenges)
Sensor for Hilo Gateway
NEW: Now configuration is done via the UI
NEW: Updates are now closer to realtime

**Comment by SanterreJo** [comment]
Très bonne idée. Je vais commencer à développer cette fonctionnalité dès que des défis Hilo seront disponibles pour pouvoir tester.

**Comment by jfmeuniercow** [comment]
Super. Merci Jonathan. Bonne journée. ________________________________Le 4 nov. 2022 à 10:29, Jonathan Santerre ***@***.***> a écrit :﻿
Très bonne idée. Je vais commencer à développer cette fonctionnalité dès que des défis Hilo seront disponibles pour pouvoir tester.

**Comment by SanterreJo** [comment]
https://github.com/SanterreJo/homebridge-hilo/releases/tag/v1.6.0
