### ISSUE TITLE
Device update

### ISSUE THREAD

**Issue by Broncobillou** [SanterreJo/homebridge-hilo#16]
Bonjour,
Encore une fois un grand merci pour le plugin. Je me répètes mais c'est de loin celui qui m'est le plus utile sur mon Raspberry.
Je ne sais pas si c'est vraiment un bug avec le plugin ou si ça vient de mon setup homebridge, mais les Device ne se mettent pas à jour après un moment et je dois redémarrer le pont Hilo. Après le redémarrage, ça revient à la normal et ça recommence après un certain temps.

Je commence à me demander si je ne devrais tout simplement pas repartir à neuf mon homebridge et tout refaire, mais je préférait en parler ici avant au cas où ce serait un bug connu.

Merci encore et bonne journée

**Comment by SanterreJo** [comment]
Oui j'ai le même problème. Je suis en train de travailler sur un fix dans cette PR #14 .

Après un certain temps, la connexion par websocket aux serveurs de Hilo est perdu et la connexion ne se rétabli pas complètement. J'ai réussi à fixer certain cas de déconnexion, par contre, il semble encore rester quelques problèmes qui causent des déconnexions lorsque les serveurs de Hilo deviennent non disponibles pendant un certain temps (à cause de mise à jour peut-être?)

**Comment by SanterreJo** [comment]
La majorité des causes de déconnexion avec le serveur de Hilo devrait être bien géré dans la version 1.4.1

**Comment by Broncobillou** [comment]
De mon côté, les informations ne se mettent pas à jour après un certain temps malgré la révision 1.4.1.

**Comment by SanterreJo** [comment]
@Broncobillou Est-ce qu'il y a des logs reliés au plugin Hilo dans Homebridge? Si oui ça pourrait donner des indices sur la cause du problème.

**Comment by Broncobillou** [comment]
Je n'ai rien vu dans les log pour le plugin Hilo. Quand j'ouvre ou ferme une lumière, ou change une consigne, ça va toujours bien. C'est lorsque je change l'état d'une lumière physiquement sur la switch ou directement sur le thermostat que ça ne se met pas à jour dans HomeKit. Dans l'app Hilo par-contre, c'est instantané.

Les automatisations fonctionnent tous par-contre, ce qui me laisse croire que la connexion est bonne.

**Comment by Broncobillou** [comment]
En fait, je n'ai plus aucun problème avec le plugin. Il se met à jour. Comme je le mentionnait, si j'ai l'application d'ouverte et que j'éteint une lumière physiquement, elle se met à jour, mais ça prend un délais plus long. Ce n'est pas bien grave en fait, car elle fini toujours par se mettre à jour.

**Comment by SanterreJo** [comment]
Content de savoir que ça fonctionne de ton côté. Au niveau du délai plus long effectivement, j'observe la même chose. Malheureusement, je crois que je n'ai pas de contrôle sur ce délai dans le plugin et que c'est un délai qui provient de HomeKit
