### ISSUE TITLE
Compatibilité Allia

### ISSUE THREAD

**Issue by SF6789** [SanterreJo/homebridge-hilo#17]
Bonjour,

Merci pour ton plugin. Je ne suis pas avec Hilo, mais Allia de Stelpro (qui est en fait exactement la même plateforme).

Pour faire fonctionner ton plugin, j'ai seulement dû modifier, dans le fichier HiloApi.js dans le dossier Dist, l'adresse "https://hilodirectoryb2c.b2clogin.com/hilodirectoryb2c.onmicrosoft.com/oauth2/v2.0/token" par "https://Stelproprod01.b2clogin.com/Stelproprod01.onmicrosoft.com/oauth2/v2.0/token" et le clientID par "a00802c5-2c33-4a90-a3ce-90b9ad14fccd" et ça fonctionne à merveille.

Par contre, à votre prochaine mise à jour, je vais devoir recommencer. Donc, je me demandais, s'il serait possible, dans une prochaine version, d'ajouter le choix de la plateforme dans la config?

**Comment by SanterreJo** [comment]
D'accord, je peux ajouter un choix de _vendor_ dans la config. Est-ce que tu peux confirmer que ça fonctionne sans avoir besoin de changer ces deux URL : `https://automation.hiloenergie.com` et `https://apim.hiloenergie.com/Automation/v1/api`. Les URL servent à obtenir les changements de status et d'envoyer des commandes aux appareils respectivement

**Comment by SF6789** [comment]
Je n'ai pas changé ces URLs et ça fonctionne très bien.
