### ISSUE TITLE
Humidité encore présente

### ISSUE THREAD

**Issue by julien-berthelot** [SanterreJo/homebridge-hilo#20]
Si je me souviens bien, dans une récente mise à jour, l’humidité était supposée être enlevée d’Homekit dans les thermostats Hilo, pourtant, je vois toujours 0% d’humidité. J’ai même enlevé le bridge HomeBridge de l’application Home et refait mon set up.
Merci!

**Comment by Broncobillou** [comment]
De mon côté aussi je vois toujours l'humidité à 0%.

**Comment by Broncobillou** [comment]
Ok super! Merci de l'information.
