### ISSUE TITLE
Trigger supplémentaires

### ISSUE THREAD

**Issue by jfmeuniercow** [SanterreJo/homebridge-hilo#29]
Allo Jonathan,

Crois-tu que c'est possible de faire un trigger à 1h Am lors d'un défi du matin et un autre pour midi lors d'un défi de soir?.

Je m'explique, lors d'un défi du matin, je monte le chauffage et autre truc à 1h du matin et les referme à 6h du matin. Cela déplace ma consommation dans cette période. Je fais la même chose pour le défi du soir. Actuellement, j'active une scène chaque fois dans l'application Hilo et je la désactive après.

Merci à toi

**Comment by SanterreJo** [comment]
Salut @jfmeuniercow, 

Je crois comprendre ton cas d'utilisation. Bien que qu'il serait possible en théorie de faire ce que tu proposes, je reste perplexe au niveau de l'implémentation. Il serait possible d'ouvrir un capteur lorsqu'il y a un défi de planifier, par contre ça ne règle pas ton cas qu'il faudrait qu'il s'active à un moment précis entre la planification et le début du défi.

**Comment by jfmeuniercow** [comment]
Allo Jonathan

Je pense que si c’était possible de faire un trigger avec l’heure du début de la phase de réduction (qui est généralement à 6 heures AM) moins 5 heures. Donc, deux trigger qui se nommerais 

Phase d’ancrage du matin (à 1h AM)
Phase d’ancrage du soir (à midi)

Est-ce possible de faire deux capteurs à l’heure de la phase de réduction moins 5 heures?

Tu peux me téléphoner si tu veux. 

Merci

 <http://jfmeunier.ca/>	
Jean-François Meunier, M. Éd, D.
450.210.0351
 <https://www.linkedin.com/in/j-fran%C3%A7ois-meunier-prof/>  <https://twitter.com/jf_meunier>  <https://www.facebook.com/j.francois.meunier>

**Comment by SanterreJo** [comment]
D'accord dans ce cas-là, ça prendrait une configuration qui permettrait de choisir le nombre d'heures avant la première phase que ces nouveaux capteurs devraient s'activer. Cela permettrait de supporter d'autres cas d'utilisations que ton cas spécifique.
