### ISSUE TITLE
New Feature

### ISSUE THREAD

**Issue by MrTeefo** [SanterreJo/homebridge-hilo#31]
i am new to homebridge and I am controlling my parent thermostat in Hilo environnement

do you have ever thing about multi account config or it is simple to doit and I mist something

thanks 

Serge

**Comment by SanterreJo** [comment]
Hi Serge, homebridge-hilo does not support multiple account. I am also not aware of multi account support in homebridge.

Maybe you could look into running a second homebridge server to keep things separate and simple.
