### ISSUE TITLE
GatewayValuesReceived

### ISSUE THREAD

**Issue by jfmeuniercow** [SanterreJo/homebridge-hilo#32]
Allo Jo.

J'ai dû réinstaller mon Homebridge au complet. J'ai maintenant un message avec le plugin Hilo.

Est-ce que tu pourrais m'aider ? Merci

[Hilo] No client method with the name 'GatewayValuesReceived' found.

**Comment by jfmeuniercow** [comment]
J'ai oublié de te dire que tout fonctionne quand même.

**Comment by jfmeuniercow** [comment]
Et j'ai cela quand je vais dans l'app Hilo.

[Hilo] No client method with the name 'DeviceListInitialValuesReceived' found.

**Comment by SanterreJo** [comment]
@jfmeuniercow merci pour l'info. J'ai validé le contenu de ces nouveaux messages et ils sont maintenant gérés et ignorés par le plugin.
