### ISSUE TITLE
Impossible de changer les thermostats avec les Scenes HomeKit

### ISSUE THREAD

**Issue by y0m1g** [SanterreJo/homebridge-hilo#34]
Bonjour Jonathan!
En essayant de mettre mes **scènes** à jour dans **HomeKit** pour cet hiver, je me suis aperçu que je ne peux plus choisir/changer la température d'aucun de mes thermostats Hilo.

Voilà ce que l'app Home (iOS 17.0.3) me donne:
<img width="293" src="https://github.com/SanterreJo/homebridge-hilo/assets/14826269/10ee5385-6c58-4560-8c11-c612453b2d72">
Impossible de faire aucun changement sur cet écran.
_(Même chose sur mon MacBook Pro (macOS 14.0) et mon iPad (iPadOS 17.0.3). J'ai aussi une Apple TV 4K et un HomePod mini tous deux en 17.0, et je ne suis pas certain de qui est le hub HomeKit principal entre iPad/AppleTV/HomePod.)_

Aussi dans Homebridge UI, les thermostats apparaissent avec des options `Off`/`Heat`/`Cool`/`Auto`, et changer ce paramètre dans cette interface n'a pas d'effet (à part le slider):
<img width="293" alt="Screenshot 2023-10-29 at 20 43 49" src="https://github.com/SanterreJo/homebridge-hilo/assets/14826269/50bd841d-5af4-4d35-bb4e-74597cc5db6a">

Je peux cependant toujours changer la température manuellement partout (dans la vue normale de l'app Home, dans Homebridge UI, et dans l'app Hilo); le problème est simplement avec les Scenes HomeKit.

Je n'ai pas d'erreur dans les logs de Homebridge (v1.6.1, HAP v0.11.1).
Je suis sur la toute dernière release de `homebridge-hilo`: v1.8.1.

Est-ce qu'il y aurait quelque chose qui aurait changé dans l'API de HomeKit qui ferait que les thermostats ne soient plus reconnus comme de simple chauffages, et qui empêche de les éditer dans les scènes?

Merci beaucoup pour ce plugin en passant! 🙂

**Comment by SanterreJo** [comment]
Après quelques tests de mon côté, j'ai pu reproduire le problème sur iOS 17.0. Ça fonctionne sur iOS 16 sur mon iPad. Semble donc être une régression au niveau d'iOS 17.0. Je n'ai toute fois pas essayer sur iOS 17.1 encore, peut-être que le problème est réglé dans cette version.

Si le problème est toujours présent dans iOS 17.1, la version `1.9.0--canary.35.0cc4735.0` contient un contournement du problème en ajoutant un mode "off" en plus de "heat". Ce qui permet de sélectionner une température dans une scène.

Je vais continuer à faire des recherches au niveau du bug reporting Apple pour voir si c'est un problème connu et s'il existe un meilleur contournement possible.

À noter que le nouveau mode "off" de la version `1.9.0--canary.35.0cc4735.0` prend un certain temps à ce reféter dans l'app. (Un restart du iPhone peut aider)

**Comment by y0m1g** [comment]
Il devait effectivement y avoir un bug côté Apple parce-qu'avec mon HomePod mini et mon iPhone en 17.1 tout marche correctement avec `1.9.0--canary.35.0cc4735.0` 🙂 (y compris sur mon iPad qui est encore 17.0.3, ce qui n'était pas le cas hier avec 17.0).
Merci beaucoup!

**Comment by SanterreJo** [comment]
J'ai pu aussi confirmer que la version iOS 17.1 résout le problème. Il n'est donc pas nécessaire d'utiliser la version avec contournement `1.9.0--canary.35.0cc4735.0`.

**Comment by y0m1g** [comment]
Juste pour confirmer que je suis revenu à 1.8.1 et que le problème est résolu avec iOS 17.1. ✅
