### ISSUE TITLE
Impossible de changer le mode et la température du thermostat dans l'app Home

### ISSUE THREAD

**Issue by y0m1g** [SanterreJo/homebridge-hilo#37]
Salut, avec le plugin v1.8.1, sous iOS 17.1 et 17.1.1, le thermostat refuse de passer à autre chose que AUTO, et la température ne peut donc pas être changée via l'app Home (de manière individuelle via scène):

https://github.com/SanterreJo/homebridge-hilo/assets/14826269/43d44c4f-5e00-41ab-b3b0-8c9ec6eaf7c5

Clairement lié à https://github.com/SanterreJo/homebridge-hilo/issues/34 et https://github.com/SanterreJo/homebridge-hilo/issues/36.
D'ailleurs et heureusement, cela marche très bien avec la branche `1.9.0--canary.35.0cc4735.0` (et donc le fix avec ici: https://github.com/SanterreJo/homebridge-hilo/pull/35).

_Je ne comprends pas pourquoi je n'ai pas eu le problème plus tôt après t'avoir pourtant confirmé que ça marchait bien avec la v1.8.1 dans iOS 17... mais le soir même j'ai vu le problème._

**Comment by SanterreJo** [comment]
Selon la vidéo que tu as envoyée, j'ai l'impression que l'app Home n'a pas rafraichi les configurations des appareils.

Je suis sur iOS 17.1.1 et la version 1.8.1 du plugin. Je ne peux pas reproduire le problème.

J'ai remarqué que l'app Home rafraichi les configurations après un redémarrage du iPhone.

Peut-être que le problème pourrait se régler en revenant à la version 1.8.1 et en redémarrant ton iPhone

**Comment by y0m1g** [comment]
Wow, effectivement je suis repassé à 1.8.1, j'ai rebooté mon iPhone (et mon HomePod Mini en même temps), et je n'ai plus le glitch! 🎉 
Merci (et désolé pour le bruit)!
