### ISSUE TITLE
Pas de declancheur pour les défis 

### ISSUE THREAD

**Issue by jfmeuniercow** [SanterreJo/homebridge-hilo#38]
Bonjour Jo 

il y a eu un défi ce matin, mais mon déclencheur planning am ne s’est pas activé. Portant, les autres ont fonctionnés (preheat, réduction et récupération) 

Est-ce que tu peux m’aider ?

merci.

**Comment by SanterreJo** [comment]
Je vais valider lorsque le prochain défi sera planifié. Il y a peut-être eu des changements au niveau de leur API, ou bien c'est une particularité des défis test

**Comment by SanterreJo** [comment]
Ça semble être un problème seulement avec le premier défi test de la saison. Je vais fermer l'issue, à moins que tu me dises que le problème est toujours présent.

**Comment by jfmeuniercow** [comment]
Allô Jonathan,Tout fonctionne maintenant. Comme tu dis, c’est sûrement avec le premier défi. Merci. ________________________________Jean-François MeunierEnvoyer de mon iPhone. Le 17 févr. 2024 à 12:25, Jonathan Santerre ***@***.***> a écrit :﻿
Ça semble être un problème seulement avec le premier défi test de la saison. Je vais fermer l'issue, à moins que tu me dises que le problème est toujours présent.
