### ISSUE TITLE
Capteur pour toute la période de défi

### ISSUE THREAD

**Issue by nboisnea** [SanterreJo/homebridge-hilo#39]
Allô! 
Tout d'abord merci beaucoup pour ce fantastique plug-in @SanterreJo !

Je me demandais pourquoi le capteur couvrant toute la période d'un défi Hilo avait été enlevé en faveur de ceux pour chaque phase? En relisant les anciennes issues je comprends le besoin pour plus de granularité, cependant voici mon cas d'usage: 
J'utilise des automatisations HomeKit pour réguler le chauffage quand je quitte ou j'arrive à la maison. Pendant un défi Hilo je désactive l'automatisation manuellement pour ne pas que mes thermostats soient enlevés du défi. J'aimerais que mon automatisation vérifie automatiquement si je suis en période de défi et ne pas toucher aux thermostats si c'est le cas. Ceux qui utilisent un peu les Shortcuts sur l'iPhone savent que ce n'est pas évident de faire des ET ou des OU avec le IF! D'où mon besoin de pouvoir vérifier facilement si je suis en défi ou non.

Je suis aussi ouvert à des solutions alternatives auxquelles je n'ai peut être pas pensé! 
Pour ceux qui utilisent les automatisations avec leur thermostats, comment faites vous? Gérez vous vous-mêmes les défis avec les capteurs sans passer par l'application Hilo?

**Comment by SanterreJo** [comment]
Bonne idée. Avoir un capteur couvrant les trois phases pourrait simplifier les automatisations. Je vais essayer de travailler là-dessus prochainement.

**Comment by GR0SL0UP** [comment]
@nboisnea Il est possible d'inclure des conditions "IF" facilement dans les automatisations d'apple Home en utilisant l'application **eve** disponible gratuitement sur le App Store.
Une fois les automatisations créées dans eve, elles apparaissent par la suite dans Home Kit et les conditions y sont visibles.
C'est ce que j'ai fait pour m'assurer que mes automatisations quotidiennes de thermostats ne se déclanchent pas si un défi en est en cours.

**Comment by SanterreJo** [comment]
Le nouveau capteur est disponible dans la version beta `v1.9.0-next.3`
