### ISSUE TITLE
Prise de courrant détecter comme lumiére au lieu de prise

### ISSUE THREAD

**Issue by tomlaf** [SanterreJo/homebridge-hilo#40]
Les prises de courrant sont présenté comme des lumière et non des prises dans HomeKit

**Comment by SanterreJo** [comment]
Je crois que la façon de faire est de changer l'option "display as" sur ta prise dans l'application Home. Je n'ai pas trouvé d'option supplémentaire dans homebridge, l'accessoire est déjà présenté comme un "outlet".

![image](https://github.com/SanterreJo/homebridge-hilo/assets/6465769/9d54a0fd-5585-4e2d-8389-1d91aa026073)
![image](https://github.com/SanterreJo/homebridge-hilo/assets/6465769/40ba8c98-99e3-4ddf-ab4f-ab2e5f79572c)

**Comment by tomlaf** [comment]
Allo,

Cette option n'est pas présente dans mon homekit.
