### ISSUE TITLE
Problème de connexion au serveur Hilo - Localisation

### ISSUE THREAD

**Issue by MarkeliMA** [SanterreJo/homebridge-hilo#41]
Depuis quelques jours, je dois redémarrer fréquemment le serveur puisque je suis déconnecté d'Hilo. En effet, voici les erreur que le système indique : 

> Unable to subscribe to location 26711 Error: An unexpected error occurred invoking 'SubscribeToLocation' on the server. HubException: 429 Too Many Requests
>     at _callbacks.<computed> (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/@microsoft/signalr/src/HubConnection.ts:417:36)
>     at HubConnection._processIncomingData (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/@microsoft/signalr/src/HubConnection.ts:558:33)
>     at WebSocketTransport.HubConnection.connection.onreceive (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/@microsoft/signalr/src/HubConnection.ts:112:57)
>     at WebSocket.webSocket.onmessage (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/@microsoft/signalr/src/WebSocketTransport.ts:104:30)
>     at WebSocket.onMessage (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/ws/lib/event-target.js:132:16)
>     at WebSocket.emit (node:events:518:28)
>     at Receiver.receiverOnMessage (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/ws/lib/websocket.js:1068:20)
>     at Receiver.emit (node:events:518:28)
>     at Receiver.dataMessage (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/ws/lib/receiver.js:517:14)
>     at Receiver.getData (/var/lib/homebridge/node_modules/homebridge-hilo/node_modules/ws/lib/receiver.js:435:17)_

Est-ce qu'il y a quelque chose à faire pour régler ce problème? 

Merci beaucoup à l'avance!

**Comment by SanterreJo** [comment]
Peut-être que Hilo ont mis des limites sur leur API. Je vais voir ce que je peux faire pour réduire le nombre d'appels que le plugin fait au serveur d'Hilo.

**Comment by SanterreJo** [comment]
Une tentative de fix est disponible dans la version beta `v1.9.0-next.3`

**Comment by ld0125** [comment]
> Une tentative de fix est disponible dans la version beta `v1.9.0-next.3`

I just installed the version v1.9.0-next.3 hopping it will solved the problem with the need of restarting hombrige because Hilo goes unresponsive and i have this error on my hombridge journal 👍 

![image](https://github.com/SanterreJo/homebridge-hilo/assets/25931488/d16d5434-244e-4a81-bb5c-8d12a7f98023)

**Comment by SanterreJo** [comment]
J'ai ajouté une logique de retry automatique donc au moins, il devrait finir par réussir à se connecter au lieu de rester en état d'erreur. Je continue d'investiguer pour trouver une solution long terme

**Comment by ld0125** [comment]
Effectivement ca fini par ce reconnecter mais après environ 1 minutes ca déconnecte. Merci pour le travail c'est vraiment apprécier !

**Comment by SanterreJo** [comment]
Je remarque que j'ai des problèmes, l'application Hilo aussi. Suis-je le seul ? Peut-être que le problème se trouve au niveau de leur serveur ?

**Comment by MarkeliMA** [comment]
Pour ma part sur l'app Hilo ça marche.

**Comment by SanterreJo** [comment]
Une nouvelle version est disponible : `1.9.0-next.4`. J'ai remarqué que l'app Hilo utilise un nouvel API. En espérant que cette API n'ait pas de limite de requête dessus. Tenez-moi au courant si le problème persiste avec cette version.

**Comment by ld0125** [comment]
Ça semble mieux à date de mon coté

**Comment by MarkeliMA** [comment]
Même chose mon côté. Pour le moment ça tient depuis la mise à jour 4.

**Comment by MarkeliMA** [comment]
L'erreur qu'il s'est mis à me faire cette nuit : ![image](https://github.com/SanterreJo/homebridge-hilo/assets/159479726/e6f0cf01-978d-43b0-9ec9-4fa975d07f87)

**Comment by MarkeliMA** [comment]
J'ai temporairement du le désactiver. Il tournait en boucle.

**Comment by ld0125** [comment]
J’ai eu le même message mais c’est revenu en ordre tout seul à 7h40 ce matin

**Comment by SanterreJo** [comment]
La nouvelle version maintenant release 1.9.0 est maintenant beaucoup plus stable. L'erreur de Location peut survenir encore, mais le plugin est plus résilient à réessayer de se connecter.
