### ISSUE TITLE
Heads up

### ISSUE THREAD

**Issue by ic-dev21** [SanterreJo/homebridge-hilo#47]
Salut. 

Juste un petit heads up. Je suis maintainer sur le projet Hilo pour HomeAssistant. 

Juste pour vous prévenir que bientôt le login via email/password en plain text ne sera plus supporté. Votre méthode de connexion actuelle sera donc fermée chez Hilo. 

Je sais pas si vous voulez entrer en contact avec eux voir si vous pouvez avoir du support pour migrer vers la nouvelle authentification. 

Petit message aussi d’essayer de limiter un peu vos calls API, on s’est déjà faits chicaner pour ça. 

Bonne soirée!

**Comment by SanterreJo** [comment]
Ok merci pour le heads up. Je me suis douté que l'authentification email/password ne serait bientôt plus supporté lorsque j'ai vu que l'app Hilo utilisait maintenant un flow d'authentification OAuth2 Client Credentials.

As-tu essayé d'entrer en contact avec Hilo pour une alternative à l'authentification user/password pour home assistant? À ta connaissance sont-ils ouvert à supporter des développeurs tiers?

**Comment by ic-dev21** [comment]
> Ok merci pour le heads up. Je me suis douté que l'authentification email/password ne serait bientôt plus supporté lorsque j'ai vu que l'app Hilo utilisait maintenant un flow d'authentification OAuth2 Client Credentials.
> 
> As-tu essayé d'entrer en contact avec Hilo pour une alternative à l'authentification user/password pour home assistant? À ta connaissance sont-ils ouvert à supporter des développeurs tiers?

Oui on a un contact à l’interne et on a pu avoir de l’aide pour la migration, je ne veux pas me prononcer à leur place par contre, c’est à eux de décider s’ils veulent y mettre du temps.

**Comment by MarkeliMA** [comment]
Je ne sais pas si c'est en lien avec la nouvelle authentification, mais voici l'erreur depuis hier. ![image](https://github.com/SanterreJo/homebridge-hilo/assets/159479726/5888694a-27ef-493f-9150-739b21e4df68)

**Comment by ic-dev21** [comment]
La vieille auth est EOL depuis hier midi.

**Comment by SanterreJo** [comment]
Je travaille présentement sur une alternative (#48). Par contre, c'est un **"travail en cours"** et ce ne sera pas prêt pour une release avant quelques jours/semaines

**Comment by maxaudet** [comment]
Si tu as besoin de testeur fais-moi signe. Je viens de tester `v2.0.0--canary.48.1fde9f2.0` mais ca ne marche pas.

Je me log à Hilo, je reviens dans HomeBridge et je vois ca
```
[4/15/2024, 6:31:13 PM] [Homebridge UI] [homebridge-hilo] Auth server listening on port 8880
[4/15/2024, 6:31:15 PM] [Homebridge UI] [homebridge-hilo] Incoming Request: /autorizationUrl
[4/15/2024, 6:31:15 PM] [Homebridge UI] [homebridge-hilo] Incoming Request: /callback
```

Mais pas de Refresh token et au reboot HomeBridge, ca me dit
`[4/15/2024, 6:32:36 PM] [homebridge-hilo] Please login with hilo in the plugin configuration page`

Merci pour ton temps!!

**Comment by ic-dev21** [comment]
Je veux pas me mêler de ce qui me regarde pas, alors feel free de me dire de me taire mais je vois la discussion passer vu que github autosubscribe par email aux issues que je crée. 

Avez-vous tenté de contacter Hilo? Perso je pense que sans un user agent/clientid pour homebridge, s’ils sont bien montés côté sécurité y’a de fortes chances que vous efforts frappent un mur. 

Vous pouvez venir faire un tour sur le discord en liens sur Hilo, on est pas sorteux. Un des devs Hilo y est actif et pourrait possiblement, sans faire le travail, vous ouvrir quelques portes. 

Je suis pas son boss alors la décision leur revient, mais c’est grâce à leur collaboration qu’on a pu rester fonctionnel de notre bord.

**Comment by SanterreJo** [comment]
@ic-dev21 La PR #48 est fonctionnelle et utilise le nouveau flow d'authentification. Ce qui reste à faire c'est de documenter et de tester que ça fonctionne avec les différentes façons d'installer un serveur homebridge. J'ai créé un nouveau thread (https://github.com/SanterreJo/homebridge-hilo/issues/50) pour permettre de suivre les bogues en lien avec la nouvelle version du plugin qui utilise la nouvelle authentification.
