### ISSUE TITLE
Nouvelle authentification Hilo

### ISSUE THREAD

**Issue by SanterreJo** [SanterreJo/homebridge-hilo#50]
Le 11 avril 2024 Hilo a mis fin à l'authentification par mot de passe. Cette issue va permettre de suivre l'avancement et les bogues en lien avec la nouvelle authentification

**Comment by SanterreJo** [comment]
>Si tu as besoin de testeur fais-moi signe. Je viens de tester v2.0.0--canary.48.1fde9f2.0 mais ca ne marche pas.
Je me log à Hilo, je reviens dans HomeBridge et je vois ca
[4/15/2024, 6:31:13 PM] [Homebridge UI] [homebridge-hilo] Auth server listening on port 8880
[4/15/2024, 6:31:15 PM] [Homebridge UI] [homebridge-hilo] Incoming Request: /autorizationUrl
[4/15/2024, 6:31:15 PM] [Homebridge UI] [homebridge-hilo] Incoming Request: /callback
Mais pas de Refresh token et au reboot HomeBridge, ca me dit
[4/15/2024, 6:32:36 PM] [homebridge-hilo] Please login with hilo in the plugin configuration page
Merci pour ton temps!!

@maxaudet peux-tu donner du détail sur ton installation homebridge (raspberrypi, docker, autre?)

**Comment by maxaudet** [comment]
Je roule dans un docker avec l'image [homebridge/homebridge](https://hub.docker.com/r/homebridge/homebridge/tags) sur un petit pc avec un Celeron donc x86

Je passe par Traefik comme reverse proxy (https://traefik.io/traefik/) donc j'ai un url genre https://homebridge.bonjour.toto

- Homebridge v1.7.0 (HAP v0.11.1)
- Node.js v18.19.0

**Comment by SanterreJo** [comment]
@maxaudet As-tu essayé de mettre `http://192.168.2.15:8880`? Sinon il faudra peut-être que tu configures ton reverse proxy pour qu'il forward le port 8880 aussi vers l'IP de ton serveur homebridge.

La façon que ça fonctionne, c'est qu'un serveur node est ouvert sur le port 8880 pendant la configuration du plugin. C'est ce serveur node qui intercepte le refresh token.

**Comment by maxaudet** [comment]
🤦 j'avais mal lu la doc et manqué le bout du 8880, en lisant vite, je pensais que ca expliquait comment trouver son URL HomeBridge. Sorry. Ca marche!
