### ISSUE TITLE
Interférence avec Home Assistant

### ISSUE THREAD

**Issue by wibyo** [SanterreJo/homebridge-hilo#51]
Lorsque je clique sur login et qu’ensuite je me connecte sur hilo, j’obtiens une page de connexion d’Home Assistant à la place, ce qui semble pas normal,
Mon Home Assistant est sur une machine virtuelle sur mon synology
Mon homebridge est sur un docker sur mon Synology

**Comment by SanterreJo** [comment]
@wibyo C'est normal. Le plugin se sert de https://my.home-assistant.io pour intercepter le refresh token de l'authentification Hilo.

Le plugin de ne se connecte pas et ne communique pas avec ton serveur homeassistant.
