### ISSUE TITLE
Impossible de s'authentifier avec Hilo

### ISSUE THREAD

**Issue by Poleri** [SanterreJo/homebridge-hilo#52]
Quand on clique sur le bouton pour initier l'authentification avec Hilo, rien ne se passe.
Aucune page, ni menu n'apparait.
Testé sur plusieurs appareils et navigateurs.

**Comment by SanterreJo** [comment]
@Poleri Lorsque tu cliques sur le bouton, ça devrait ouvrir un nouveau tab ou une nouvelle fenêtre dans ton navigateur.

Je viens d'essayer et ça fonctionne de mon côté. Est-ce que ça se pourrait qu'il y ait quelque chose qui bloque les popups  de ton côté ?

Il y a peut-être une erreur dans la console de ton navigateur. Tu peux voir ces messages dans les outils de développeurs dans la console.

**Comment by Poleri** [comment]
Salut,
Merci pour ton commentaire.
Et non malheureusement, aucun fenêtre ne pop, ni message d'erreur dans la console...
Je l'ai testé sur 2 PC différents (Mac & Windows), sur plusieurs navigateurs également et le comportement est le même à chaque fois...
Si le seul pour qui cela ne fonctionne pas?
Merci
