### ISSUE TITLE
Authenticate button not working 

### ISSUE THREAD

**Issue by dangerxtrem** [SanterreJo/homebridge-hilo#53]
Hi, 

I installed the latest version of the Hilo plugin on my home bridge (latest version) and when I start the authentication process by clicking the button, it does nothing.

**Comment by jacklibb** [comment]
I managed to get to “Success - You can now close this page”, but when I save and restart homebridge, the config icon is still flashing on the plugins page and I don’t see my accessories pop up.

**Comment by SanterreJo** [comment]
@jacklibb When you open the plugin configuration, does the "Refresh token" field has something in it or is it empty?

**Comment by jacklibb** [comment]
![image](https://github.com/user-attachments/assets/1a66a7a8-5e98-448b-beed-7681079dfd5a)
I don't see a "Refresh token" field in the interface. I tried both v2.0.0 (latest) and v2.0.0 (canary).

**Comment by jacklibb** [comment]
I was able to fix it by manually adding a Child Bridge in the JSON config file on the Homebridge UI followed by a restart.

![image](https://github.com/user-attachments/assets/227a558a-b983-440e-a6c7-2cff05f0d08d)

**Comment by SanterreJo** [comment]
@jacklibb Your last comment made me realize that the bug was probably reproducible on new installations. And it indeed it was.

I was able to find the issue and fix was released in v2.0.1.
