### ISSUE TITLE
Pas capable de configurer.

### ISSUE THREAD

**Issue by justinjsp** [SanterreJo/homebridge-hilo#56]
Pas capable de configurer. Je fais le tout pour le connecter, je rentre mes infos et je valide avec le site Hilo, mais finalement, ça fait genre un loop. Même pas capable de créer un "child bridge". C'est une nouvelle installation de Hilo. 

Merci d'avance!

**Comment by SanterreJo** [comment]
Quand tu dis "ça fait genre un loop", peux-tu donner plus de détail ?

À quel endroit ça cesse de fonctionner ?

Une vidéo ou une description détaillée étape par étape pourrait aider à trouver la source du problème.

**Comment by justinjsp** [comment]
Ça marche parfaitement maintenant. Je pense que c’était plutôt du user error. 🤪Merci!Justin PrestOn Oct 26, 2024, at 10:32, Jonathan Santerre ***@***.***> wrote:﻿
Quand tu dis "ça fait genre un loop", peux-tu donner plus de détail ?
À quel endroit ça cesse de fonctionner ?
Une vidéo ou une description détaillée étape par étape pourrait aider à trouver la source du problème.
