### ISSUE TITLE
10 oC Temperature limit setpoint

### ISSUE THREAD

**Issue by Broncobillou** [SanterreJo/homebridge-hilo#9]
Hi,
Thank you very much for the plugin. It's so far the best one for me.
I just want to report something. The thermostat set point, in the hilo app,  can be set to 5oC.
The problem is that in the HomeKit app, I can't put the set point below 10oC.
I have one thermostat in the garage so it could be very useful to change the set point lower then 10oC to have the same possibility then on the Hilo app.

Thank you and have a nice day

**Comment by lemontv** [comment]
I think 10 degree Celsius is recommend for any room. Lower than this will damage your house.

**Comment by Broncobillou** [comment]
Maybe, but Hilo apps allow us to reach 5oC.In the garage, 10oC is to High when winter is coming. It could be very nice to have the same range on both apps. If they set the minimum range to 5oC, it’s probably ok to lower at this minimum.Have a nice dayLe 6 oct. 2022 à 23:22, Shiming Chen ***@***.***> a écrit :﻿
I think 10 degree Celsius is recommend for any room. Lower than this will damage your house.

**Comment by SanterreJo** [comment]
@Broncobillou this issue is now resolved and a new version of the package is now published (1.3.0).

Min target temperature is now 5C, max is now 30C and temperature steps are 0.5C which reflect Hilo thermostat's hardware capabilities

**Comment by Broncobillou** [comment]
Thank you very much.
I very much appreciate your support.
Have a nice day.
